DROP TABLE "TB_GRADE";
DROP TABLE "TB_STUDENT";
DROP TABLE "TB_CLASS_PROFESSOR";
DROP TABLE "TB_CLASS";
DROP TABLE "TB_PROFESSOR";
DROP TABLE "TB_DEPARTMENT";

CREATE TABLE "TB_DEPARTMENT" (
	"DEPARTMENT_NO"	VARCHAR2(20)		NOT NULL,
	"DEPARTMENT_NAME"	VARCHAR2(20)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NULL,
	"OPEN_YN"	CHAR(1)		NULL,
	"CAPACITY"	NUMBER		NULL
);

COMMENT ON COLUMN "TB_DEPARTMENT"."DEPARTMENT_NO" IS '학과 번호';
COMMENT ON COLUMN "TB_DEPARTMENT"."DEPARTMENT_NAME" IS '학과 이름';
COMMENT ON COLUMN "TB_DEPARTMENT"."CATEGORY" IS '계열';
COMMENT ON COLUMN "TB_DEPARTMENT"."OPEN_YN" IS '개설 여부';
COMMENT ON COLUMN "TB_DEPARTMENT"."CAPACITY" IS '정원';

CREATE TABLE "TB_STUDENT" (
	"STUDENT_NO"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_NO"	VARCHAR2(20)		NOT NULL,
	"STUDENT_NAME"	VARCHAR2(30)		NOT NULL,
	"STUDENT_SSN"	VARCHAR2(14)		NULL,
	"STUDENT_ADDRESS"	VARCHAR2(100)		NULL,
	"ENTRANCE_DATE"	DATE		NULL,
	"ABSENCE_YN"	CHAR(1)		NULL,
	"COACH_PROFESSOR_NO"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TB_STUDENT"."STUDENT_NO" IS '학생 번호';
COMMENT ON COLUMN "TB_STUDENT"."DEPARTMENT_NO" IS '학과 번호';
COMMENT ON COLUMN "TB_STUDENT"."STUDENT_NAME" IS '학생 이름';
COMMENT ON COLUMN "TB_STUDENT"."STUDENT_SSN" IS '학생 주민번호';
COMMENT ON COLUMN "TB_STUDENT"."STUDENT_ADDRESS" IS '학생 주소';
COMMENT ON COLUMN "TB_STUDENT"."ENTRANCE_DATE" IS '입학 일자';
COMMENT ON COLUMN "TB_STUDENT"."ABSENCE_YN" IS '휴학 여부';
COMMENT ON COLUMN "TB_STUDENT"."COACH_PROFESSOR_NO" IS '지도 교수 번호';

CREATE TABLE "TB_CLASS_PROFESSOR" (
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"PROFESSOR_NO"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TB_CLASS_PROFESSOR"."CLASS_NO" IS '과목 번호';
COMMENT ON COLUMN "TB_CLASS_PROFESSOR"."PROFESSOR_NO" IS '교수 번호';

CREATE TABLE "TB_CLASS" (
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_NO"	VARCHAR2(20)		NOT NULL,
	"PREATTENDING_CLASS_NO"	VARCHAR2(10)		NULL,
	"CLASS_NAME"	VARCHAR2(60)		NOT NULL,
	"CLASS_TYPE"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "TB_CLASS"."CLASS_NO" IS '과목 번호';
COMMENT ON COLUMN "TB_CLASS"."DEPARTMENT_NO" IS '학과 번호';
COMMENT ON COLUMN "TB_CLASS"."PREATTENDING_CLASS_NO" IS '선수 과목 번호';
COMMENT ON COLUMN "TB_CLASS"."CLASS_NAME" IS '과목 이름';
COMMENT ON COLUMN "TB_CLASS"."CLASS_TYPE" IS '과목 구분';

CREATE TABLE "TB_PROFESSOR" (
	"PROFESSOR_NO"	VARCHAR2(10)		NOT NULL,
	"PROFESSOR_NAME"	VARCHAR2(30)		NOT NULL,
	"PROFESSOR_SSN"	VARCHAR2(14)		NULL,
	"PROFESSOR_ADDRESS"	VARCHAR2(100)		NULL,
	"DEPARTMENT_NO"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "TB_PROFESSOR"."PROFESSOR_NO" IS '교수 번호';
COMMENT ON COLUMN "TB_PROFESSOR"."PROFESSOR_NAME" IS '교수 이름';
COMMENT ON COLUMN "TB_PROFESSOR"."PROFESSOR_SSN" IS '교수 주민번호';
COMMENT ON COLUMN "TB_PROFESSOR"."PROFESSOR_ADDRESS" IS '교수 주소';
COMMENT ON COLUMN "TB_PROFESSOR"."DEPARTMENT_NO" IS '학과 번호';

CREATE TABLE "TB_GRADE" (
	"TERM_NO"	VARCHAR2(10)		NOT NULL,
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"STUDENT_NO"	VARCHAR2(10)		NOT NULL,
	"POINT"	NUMBER(3,2)		NULL
);

COMMENT ON COLUMN "TB_GRADE"."TERM_NO" IS '학기 번호';
COMMENT ON COLUMN "TB_GRADE"."CLASS_NO" IS '과목 번호';
COMMENT ON COLUMN "TB_GRADE"."STUDENT_NO" IS '학생 번호';
COMMENT ON COLUMN "TB_GRADE"."POINT" IS '학점';

ALTER TABLE "TB_DEPARTMENT" ADD CONSTRAINT "PK_TB_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_NO"
);
ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "PK_TB_STUDENT" PRIMARY KEY (
	"STUDENT_NO"
);
ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "PK_TB_CLASS_PROFESSOR" PRIMARY KEY (
	"CLASS_NO",
	"PROFESSOR_NO"
);
ALTER TABLE "TB_CLASS" ADD CONSTRAINT "PK_TB_CLASS" PRIMARY KEY (
	"CLASS_NO"
);
ALTER TABLE "TB_PROFESSOR" ADD CONSTRAINT "PK_TB_PROFESSOR" PRIMARY KEY (
	"PROFESSOR_NO"
);
ALTER TABLE "TB_GRADE" ADD CONSTRAINT "PK_TB_GRADE" PRIMARY KEY (
	"TERM_NO",
	"CLASS_NO",
	"STUDENT_NO"
);
ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_STUDENT_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);
ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "FK_TB_PROFESSOR_TO_TB_STUDENT_1" FOREIGN KEY (
	"COACH_PROFESSOR_NO"
)
REFERENCES "TB_PROFESSOR" (
	"PROFESSOR_NO"
);
ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "FK_TB_CLASS_TO_TB_CLASS_PROFESSOR_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "TB_CLASS" (
	"CLASS_NO"
);
ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "FK_TB_PROFESSOR_TO_TB_CLASS_PROFESSOR_1" FOREIGN KEY (
	"PROFESSOR_NO"
)
REFERENCES "TB_PROFESSOR" (
	"PROFESSOR_NO"
);
ALTER TABLE "TB_CLASS" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_CLASS_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);
ALTER TABLE "TB_PROFESSOR" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_PROFESSOR_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);
ALTER TABLE "TB_GRADE" ADD CONSTRAINT "FK_TB_CLASS_TO_TB_GRADE_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "TB_CLASS" (
	"CLASS_NO"
);

ALTER TABLE "TB_GRADE" ADD CONSTRAINT "FK_TB_STUDENT_TO_TB_GRADE_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "TB_STUDENT" (
	"STUDENT_NO"
);

INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('001', '국어국문학과', '인문사회', 'Y', 20);
INSERT INTO TB_DEPARTMENT (DEPARTMENT_NO, DEPARTMENT_NAME, CATEGORY, OPEN_YN, CAPACITY)
VALUES ('002', '영어영문학과', '인문사회', 'Y', 36);

INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0245500', '001', NULL, '고전시가론특강', '전공선택');
INSERT INTO TB_CLASS (CLASS_NO, DEPARTMENT_NO, PREATTENDING_CLASS_NO, CLASS_NAME, CLASS_TYPE)
VALUES ('C0405000', '001', NULL, '국어어휘론특강', '전공선택');

INSERT INTO TB_PROFESSOR (PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_SSN, PROFESSOR_ADDRESS, DEPARTMENT_NO)
VALUES ('P001', '김진영', '500530-1102646', '서울시 강서구 등촌1동 대동아파트103-704', '001');
INSERT INTO TB_PROFESSOR (PROFESSOR_NO, PROFESSOR_NAME, PROFESSOR_SSN, PROFESSOR_ADDRESS, DEPARTMENT_NO)
VALUES ('P002', '양윤필', '670510-1158493', '서울시 광진구 하양동 111-12', '002');

INSERT INTO TB_CLASS_PROFESSOR (CLASS_NO, PROFESSOR_NO)
VALUES ('C0245500', 'P001');
INSERT INTO TB_CLASS_PROFESSOR (CLASS_NO, PROFESSOR_NO)
VALUES ('C0245500', 'P002');

INSERT INTO TB_STUDENT (STUDENT_NO, DEPARTMENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS, ENTRANCE_DATE, ABSENCE_YN, COACH_PROFESSOR_NO)
VALUES ('A213046', '001', '서가람', '830530-2124663', '경기도 군포시 산본동 1052번지 대림아파트 724-301호', to_date('01-03-2002', 'dd-mm-yyyy'), 'N', 'P001');
INSERT INTO TB_STUDENT (STUDENT_NO, DEPARTMENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS, ENTRANCE_DATE, ABSENCE_YN, COACH_PROFESSOR_NO)
VALUES ('A612025', '001', '김광인', '870712-1122991', '서울시 송파구 마천2동 금호베스트빌아파트 103-104호', to_date('01-03-2006', 'dd-mm-yyyy'), 'N', 'P001');

INSERT INTO TB_GRADE (TERM_NO, STUDENT_NO, CLASS_NO, POINT)
VALUES ('200601', 'A612025', 'C0245500', 1.5);
INSERT INTO TB_GRADE (TERM_NO, STUDENT_NO, CLASS_NO, POINT)
VALUES ('200602', 'A612025', 'C0245500', 3.5);

commit;
select * from tb_student where department_no = '001';