-- TALK
insert into MEMBER values ('jiin0960', '0960','jin', 'a1@gmail.com');
insert into MEMBER values ('sony0316', '0316','soni', 'a2@gmail.com');
insert into MEMBER values ('onue0608', '0608','nue', 'a3@gmail.com');
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST1', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST2', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST3', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST4', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST5', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST6', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST7', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST8', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST9', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST10', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST11', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST12', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST13', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST14', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST15', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST16', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST17', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST18', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST19', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST20', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST21', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST22', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST23', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST24', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST25', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST26', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST27', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST28', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST29', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST30', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST31', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST32', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST33', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST34', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST35', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST36', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST37', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST38', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST39', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST40', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST41', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST42', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST43', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST44', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST45', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST46', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST47', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST48', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST49', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST50', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST51', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST52', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST53', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST54', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST55', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST56', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST57', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST58', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST59', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST60', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST61', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST62', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST63', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST64', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST65', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST66', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST67', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST68', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST69', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST70', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST71', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST72', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST73', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST74', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST75', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST76', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST77', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST78', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST79', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST80', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST81', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST82', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST83', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST84', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST85', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST86', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST87', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST88', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST89', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST90', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST91', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST92', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST93', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST94', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST95', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST96', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST97', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST98', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST99', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST100', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST101', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST102', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST103', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST104', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST105', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST106', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST107', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST108', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST109', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST110', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST111', 'ㅋㅋ', 'sony0316', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST112', 'ㅋㅋㅋ', 'onue0608', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0) ;
COMMIT;

-- JJAP KOREA
insert into MEMBER values ('jiin0960', 'jin', default, default, default, default, default);
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST1', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST2', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST3', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST4', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST5', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST6', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST7', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST8', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST9', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST10', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST11', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST12', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST13', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST14', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST15', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST16', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST17', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST18', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST19', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST20', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST21', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST22', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST23', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST24', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST25', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST26', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST27', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST28', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST29', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST30', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST31', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST32', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST33', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST34', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST35', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST36', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST37', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST38', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST39', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST40', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST41', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST42', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST43', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST44', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST45', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST46', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST47', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST48', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST49', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST50', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST51', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST52', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST53', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST54', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST55', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST56', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST57', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST58', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST59', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST60', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST61', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST62', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST63', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST64', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST65', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST66', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST67', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST68', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST69', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST70', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST71', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST72', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST73', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST74', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST75', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST76', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST77', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST78', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST79', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST80', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST81', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST82', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST83', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST84', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST85', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST86', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST87', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST88', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST89', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST90', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST91', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST92', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST93', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST94', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST95', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST96', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST97', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST98', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST99', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST100', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST101', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST102', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST103', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST104', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST105', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST106', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST107', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST108', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST109', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST110', 'ㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST111', 'ㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
insert into BOARD values (SEQ_BOARD_BNO.nextval, 'TEST112', 'ㅋㅋㅋ', 'jiin0960', default, 0, SEQ_BOARD_BNO.nextval, 0, 0, 0, 0) ;
COMMIT;