DROP TABLE BOARD;

CREATE TABLE "BOARD" (
	"BNO"	NUMBER		NOT NULL,
	"BTITLE"	VARCHAR2(300)		NOT NULL,
	"BCONTENT"	VARCHAR2(4000)		NULL,
	"BWRITE_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"MID"	VARCHAR2(20)		NOT NULL,
	"BREF"	NUMBER		NOT NULL,
	"BRE_LEVEL"	NUMBER		NOT NULL,
	"BRE_STEP"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BNO" IS 'SEQ_BOARD_BNO 사용';
COMMENT ON COLUMN "BOARD"."BTITLE" IS '제목';
COMMENT ON COLUMN "BOARD"."BCONTENT" IS '글내용';
COMMENT ON COLUMN "BOARD"."BWRITE_DATE" IS '작성시간';
COMMENT ON COLUMN "BOARD"."MID" IS '작성자';
COMMENT ON COLUMN "BOARD"."BREF" IS 'BNO=BREF:원본글, BNO<>BREF:답..글';
COMMENT ON COLUMN "BOARD"."BRE_LEVEL" IS '0:원본글, 1:답글, 2:답답글...';
COMMENT ON COLUMN "BOARD"."BRE_STEP" IS '0:원본글, 1-N 원본글기준답..글들의순서';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BNO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);